### ISSUE TITLE
提案(issueではないかも)

### ISSUE THREAD

**Issue by gamesukimanIRS** [itsu020402/MCBEFormMaker#1]
こちらのアプリでフォームを作成し、エクスポートする際に、中身が書き込まれたjava/php/jsonになって出力されるのですが、違うファイルのjsonを吸い出して代入する術など持ち合わせておらず、出力したものを開いてコピペしています。

この出力したものを開いての手順がいらないものだと思うので、ファイルに保存はせずに直接コードを別ウィンドウ等で表示するのはいかがでしょうか？

その方がコピペしやすいかと...

**Comment by itsu020402** [comment]
提案ありがとうございます。
その機能はalpha2.1の
メニューバーの「開発」の「Jsonビューワ」セクションからお使いいただけます。

**Comment by gamesukimanIRS** [comment]
ありがとうございます。
既にあったことを知りませんでした()
すみません。
